<?php

$days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
$classrooms = ['CR01','CR02','CR03'];
$periods = ['8.00am - 9.00am', '9.00am - 10.00am','10.00am - 11.00am','11.00am - 12.00pm','12.00pm - 1.00pm','1.00pm - 2.00pm','2.00pm - 3.00pm','3.00pm - 4.00pm','4.00pm - 5.00pm','5.00pm - 6.00pm','6.00pm - 7.00pm','7.00pm - 8.00pm','8.00pm - 9.00pm','9.00pm - 10.00pm'];
$fetch_row_count=1;

for($i=0;$i<count($days);$i++){
	$day = $days[$i];
	for($j=0;$j<count($classrooms);$j++){
		$classroom= $classrooms[$j];
		for($k=0;$k<count($periods);$k++){
			$period = $periods[$k];
			${"result".$fetch_row_count}=mysqli_query($conn,"select *  from schedule where schedule.Day = '$day' and venue='$classroom' and time='$period'");
			${"row".$fetch_row_count}=mysqli_fetch_assoc(${"result".$fetch_row_count});
			$fetch_row_count++;
		}
	}
}

 //Timetable Monday
 /*
 $result1=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='8.00am - 9.00am' and schedule.Venue='CR01'");
 $result2=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='9.00am - 10.00am' and schedule.Venue='CR01' ");
 $result3=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='10.00am - 11.00am' and schedule.Venue='CR01' ");
 $result4=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='11.00am - 12.00pm' and schedule.Venue='CR01' ");
 $result5=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='12.00pm - 1.00pm' and schedule.Venue='CR01' ");
 $result6=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='1.00pm - 2.00pm' and schedule.Venue='CR01' ");
 $result7=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='2.00pm - 3.00pm' and schedule.Venue='CR01' ");
 $result8=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='3.00pm - 4.00pm' and schedule.Venue='CR01' ");
 $result9=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='4.00pm - 5.00pm' and schedule.Venue='CR01' ");
 $result10=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='5.00pm - 6.00pm' and schedule.Venue='CR01' ");
 $result11=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='6.00pm - 7.00pm' and schedule.Venue='CR01' ");
 $result12=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='7.00pm - 8.00pm' and schedule.Venue='CR01' ");
 $result13=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='8.00pm - 9.00pm' and schedule.Venue='CR01' ");
 $result14=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='9.00pm - 10.00pm' and schedule.Venue='CR01' ");
 
 $row1=mysqli_fetch_assoc($result1);
 $row2=mysqli_fetch_assoc($result2);
 $row3=mysqli_fetch_assoc($result3);
 $row4=mysqli_fetch_assoc($result4);
 $row5=mysqli_fetch_assoc($result5);
 $row6=mysqli_fetch_assoc($result6);
 $row7=mysqli_fetch_assoc($result7);
 $row8=mysqli_fetch_assoc($result8);
 $row9=mysqli_fetch_assoc($result9);
 $row10=mysqli_fetch_assoc($result10);
 $row11=mysqli_fetch_assoc($result11);
 $row12=mysqli_fetch_assoc($result12);
 $row13=mysqli_fetch_assoc($result13);
 $row14=mysqli_fetch_assoc($result14);
 
 $result15=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='8.00am - 9.00am' and schedule.Venue='CR02' ");
 $result16=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='9.00am - 10.00am' and schedule.Venue='CR02' ");
 $result17=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='10.00am - 11.00am' and schedule.Venue='CR02' ");
 $result18=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='11.00am - 12.00pm' and schedule.Venue='CR02' ");
 $result19=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='12.00pm - 1.00pm' and schedule.Venue='CR02' ");
 $result20=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='1.00pm - 2.00pm' and schedule.Venue='CR02' ");
 $result21=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='2.00pm - 3.00pm' and schedule.Venue='CR02' ");
 $result22=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='3.00pm - 4.00pm' and schedule.Venue='CR02' ");
 $result23=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='4.00pm - 5.00pm' and schedule.Venue='CR02' ");
 $result24=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='5.00pm - 6.00pm' and schedule.Venue='CR02' ");
 $result25=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='6.00pm - 7.00pm' and schedule.Venue='CR02' ");
 $result26=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='7.00pm - 8.00pm' and schedule.Venue='CR02' ");
 $result27=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='8.00pm - 9.00pm' and schedule.Venue='CR02' ");
 $result28=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='9.00pm - 10.00pm' and schedule.Venue='CR02' ");
 $row15=mysqli_fetch_assoc($result15);
 $row16=mysqli_fetch_assoc($result16);
 $row17=mysqli_fetch_assoc($result17);
 $row18=mysqli_fetch_assoc($result18);
 $row19=mysqli_fetch_assoc($result19);
 $row20=mysqli_fetch_assoc($result20);
 $row21=mysqli_fetch_assoc($result21);
 $row22=mysqli_fetch_assoc($result22);
 $row23=mysqli_fetch_assoc($result23);
 $row24=mysqli_fetch_assoc($result24);
 $row25=mysqli_fetch_assoc($result25);
 $row26=mysqli_fetch_assoc($result26);
 $row27=mysqli_fetch_assoc($result27);
 $row28=mysqli_fetch_assoc($result28);
 
 $result29=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='8.00am - 9.00am' and schedule.Venue='CR03' ");
 $result30=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='9.00am - 10.00am' and schedule.Venue='CR03' ");
 $result31=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='10.00am - 11.00am' and schedule.Venue='CR03' ");
 $result32=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='11.00am - 12.00pm' and schedule.Venue='CR03' ");
 $result33=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='12.00pm - 1.00pm' and schedule.Venue='CR03' ");
 $result34=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='1.00pm - 2.00pm' and schedule.Venue='CR03' ");
 $result35=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='2.00pm - 3.00pm' and schedule.Venue='CR03' ");
 $result36=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='3.00pm - 4.00pm' and schedule.Venue='CR03' ");
 $result37=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='4.00pm - 5.00pm' and schedule.Venue='CR03' ");
 $result38=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='5.00pm - 6.00pm' and schedule.Venue='CR03' ");
 $result39=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='6.00pm - 7.00pm' and schedule.Venue='CR03' ");
 $result40=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='7.00pm - 8.00pm' and schedule.Venue='CR03' ");
 $result41=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='8.00pm - 9.00pm' and schedule.Venue='CR03' ");
 $result42=mysqli_query($conn,"select *  from schedule where schedule.Day='Monday' and time='9.00pm - 10.00pm' and schedule.Venue='CR03' ");
 $row29=mysqli_fetch_assoc($result29);
 $row30=mysqli_fetch_assoc($result30);
 $row31=mysqli_fetch_assoc($result31);
 $row32=mysqli_fetch_assoc($result32);
 $row33=mysqli_fetch_assoc($result33);
 $row34=mysqli_fetch_assoc($result34);
 $row35=mysqli_fetch_assoc($result35);
 $row36=mysqli_fetch_assoc($result36);
 $row37=mysqli_fetch_assoc($result37);
 $row38=mysqli_fetch_assoc($result38);
 $row39=mysqli_fetch_assoc($result39);
 $row40=mysqli_fetch_assoc($result40);
 $row41=mysqli_fetch_assoc($result41);
 $row42=mysqli_fetch_assoc($result42);
 
 //Timetable Tuesday
 
 $result43=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='8.00am - 9.00am' and schedule.Venue='CR01' ");
 $result44=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='9.00am - 10.00am' and schedule.Venue='CR01' ");
 $result45=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='10.00am - 11.00am' and schedule.Venue='CR01' ");
 $result46=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='11.00am - 12.00pm' and schedule.Venue='CR01' ");
 $result47=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='12.00pm - 1.00pm' and schedule.Venue='CR01' ");
 $result48=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='1.00pm - 2.00pm' and schedule.Venue='CR01' ");
 $result49=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='2.00pm - 3.00pm' and schedule.Venue='CR01' ");
 $result50=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='3.00pm - 4.00pm' and schedule.Venue='CR01' ");
 $result51=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='4.00pm - 5.00pm' and schedule.Venue='CR01' ");
 $result52=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='5.00pm - 6.00pm' and schedule.Venue='CR01' ");
 $result53=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='6.00pm - 7.00pm' and schedule.Venue='CR01' ");
 $result54=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='7.00pm - 8.00pm' and schedule.Venue='CR01' ");
 $result55=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='8.00pm - 9.00pm' and schedule.Venue='CR01' ");
 $result56=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='9.00pm - 10.00pm' and schedule.Venue='CR01' ");
 $row43=mysqli_fetch_assoc($result43);
 $row44=mysqli_fetch_assoc($result44);
 $row45=mysqli_fetch_assoc($result45);
 $row46=mysqli_fetch_assoc($result46);
 $row47=mysqli_fetch_assoc($result47);
 $row48=mysqli_fetch_assoc($result48);
 $row49=mysqli_fetch_assoc($result49);
 $row50=mysqli_fetch_assoc($result50);
 $row51=mysqli_fetch_assoc($result51);
 $row52=mysqli_fetch_assoc($result52);
 $row53=mysqli_fetch_assoc($result53);
 $row54=mysqli_fetch_assoc($result54);
 $row55=mysqli_fetch_assoc($result55);
 $row56=mysqli_fetch_assoc($result56);
 
 $result57=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='8.00am - 9.00am' and schedule.Venue='CR02' ");
 $result58=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='9.00am - 10.00am' and schedule.Venue='CR02' ");
 $result59=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='10.00am - 11.00am' and schedule.Venue='CR02' ");
 $result60=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='11.00am - 12.00pm' and schedule.Venue='CR02' ");
 $result61=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='12.00pm - 1.00pm' and schedule.Venue='CR02' ");
 $result62=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='1.00pm - 2.00pm' and schedule.Venue='CR02' ");
 $result63=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='2.00pm - 3.00pm' and schedule.Venue='CR02' ");
 $result64=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='3.00pm - 4.00pm' and schedule.Venue='CR02' ");
 $result65=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='4.00pm - 5.00pm' and schedule.Venue='CR02' ");
 $result66=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='5.00pm - 6.00pm' and schedule.Venue='CR02' ");
 $result67=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='6.00pm - 7.00pm' and schedule.Venue='CR02' ");
 $result68=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='7.00pm - 8.00pm' and schedule.Venue='CR02' ");
 $result69=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='8.00pm - 9.00pm' and schedule.Venue='CR02' ");
 $result70=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='9.00pm - 10.00pm' and schedule.Venue='CR02' ");
 $row57=mysqli_fetch_assoc($result57);
 $row58=mysqli_fetch_assoc($result58);
 $row59=mysqli_fetch_assoc($result59);
 $row60=mysqli_fetch_assoc($result60);
 $row61=mysqli_fetch_assoc($result61);
 $row62=mysqli_fetch_assoc($result62);
 $row63=mysqli_fetch_assoc($result63);
 $row64=mysqli_fetch_assoc($result64);
 $row65=mysqli_fetch_assoc($result65);
 $row66=mysqli_fetch_assoc($result66);
 $row67=mysqli_fetch_assoc($result67);
 $row68=mysqli_fetch_assoc($result68);
 $row69=mysqli_fetch_assoc($result69);
 $row70=mysqli_fetch_assoc($result70);
 
 $result71=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='8.00am - 9.00am' and schedule.Venue='CR03' ");
 $result72=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='9.00am - 10.00am' and schedule.Venue='CR03' ");
 $result73=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='10.00am - 11.00am' and schedule.Venue='CR03' ");
 $result74=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='11.00am - 12.00pm' and schedule.Venue='CR03' ");
 $result75=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='12.00pm - 1.00pm' and schedule.Venue='CR03' ");
 $result76=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='1.00pm - 2.00pm' and schedule.Venue='CR03' ");
 $result77=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='2.00pm - 3.00pm' and schedule.Venue='CR03' ");
 $result78=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='3.00pm - 4.00pm' and schedule.Venue='CR03' ");
 $result79=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='4.00pm - 5.00pm' and schedule.Venue='CR03' ");
 $result80=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='5.00pm - 6.00pm' and schedule.Venue='CR03' ");
 $result81=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='6.00pm - 7.00pm' and schedule.Venue='CR03' ");
 $result82=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='7.00pm - 8.00pm' and schedule.Venue='CR03' ");
 $result83=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='8.00pm - 9.00pm' and schedule.Venue='CR03' ");
 $result84=mysqli_query($conn,"select *  from schedule where schedule.Day='Tuesday' and time='9.00pm - 10.00pm' and schedule.Venue='CR03' ");
 $row71=mysqli_fetch_assoc($result71);
 $row72=mysqli_fetch_assoc($result72);
 $row73=mysqli_fetch_assoc($result73);
 $row74=mysqli_fetch_assoc($result74);
 $row75=mysqli_fetch_assoc($result75);
 $row76=mysqli_fetch_assoc($result76);
 $row77=mysqli_fetch_assoc($result77);
 $row78=mysqli_fetch_assoc($result78);
 $row79=mysqli_fetch_assoc($result79);
 $row80=mysqli_fetch_assoc($result80);
 $row81=mysqli_fetch_assoc($result81);
 $row82=mysqli_fetch_assoc($result82);
 $row83=mysqli_fetch_assoc($result83);
 $row84=mysqli_fetch_assoc($result84);
 
 //Timetable Wednesday
 
 $result85=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='8.00am - 9.00am' and schedule.Venue='CR01' ");
 $result86=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='9.00am - 10.00am' and schedule.Venue='CR01' ");
 $result87=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='10.00am - 11.00am' and schedule.Venue='CR01' ");
 $result88=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='11.00am - 12.00pm' and schedule.Venue='CR01' ");
 $result89=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='12.00pm - 1.00pm' and schedule.Venue='CR01' ");
 $result90=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='1.00pm - 2.00pm' and schedule.Venue='CR01' ");
 $result91=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='2.00pm - 3.00pm' and schedule.Venue='CR01' ");
 $result92=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='3.00pm - 4.00pm' and schedule.Venue='CR01' ");
 $result93=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='4.00pm - 5.00pm' and schedule.Venue='CR01' ");
 $result94=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='5.00pm - 6.00pm' and schedule.Venue='CR01' ");
 $result95=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='6.00pm - 7.00pm' and schedule.Venue='CR01' ");
 $result96=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='7.00pm - 8.00pm' and schedule.Venue='CR01' ");
 $result97=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='8.00pm - 9.00pm' and schedule.Venue='CR01' ");
 $result98=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='9.00pm - 10.00pm' and schedule.Venue='CR01' ");
 $row85=mysqli_fetch_assoc($result85);
 $row86=mysqli_fetch_assoc($result86);
 $row87=mysqli_fetch_assoc($result87);
 $row88=mysqli_fetch_assoc($result88);
 $row89=mysqli_fetch_assoc($result89);
 $row90=mysqli_fetch_assoc($result90);
 $row91=mysqli_fetch_assoc($result91);
 $row92=mysqli_fetch_assoc($result92);
 $row93=mysqli_fetch_assoc($result93);
 $row94=mysqli_fetch_assoc($result94);
 $row95=mysqli_fetch_assoc($result95);
 $row96=mysqli_fetch_assoc($result96);
 $row97=mysqli_fetch_assoc($result97);
 $row98=mysqli_fetch_assoc($result98);
 
 $result99=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='8.00am - 9.00am' and schedule.Venue='CR02' ");
 $result100=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='9.00am - 10.00am' and schedule.Venue='CR02' ");
 $result101=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='10.00am - 11.00am' and schedule.Venue='CR02' ");
 $result102=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='11.00am - 12.00pm' and schedule.Venue='CR02' ");
 $result103=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='12.00pm - 1.00pm' and schedule.Venue='CR02' ");
 $result104=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='1.00pm - 2.00pm' and schedule.Venue='CR02' ");
 $result105=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='2.00pm - 3.00pm' and schedule.Venue='CR02' ");
 $result106=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='3.00pm - 4.00pm' and schedule.Venue='CR02' ");
 $result107=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='4.00pm - 5.00pm' and schedule.Venue='CR02' ");
 $result108=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='5.00pm - 6.00pm' and schedule.Venue='CR02' ");
 $result109=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='6.00pm - 7.00pm' and schedule.Venue='CR02' ");
 $result110=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='7.00pm - 8.00pm' and schedule.Venue='CR02' ");
 $result111=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='8.00pm - 9.00pm' and schedule.Venue='CR02' ");
 $result112=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='9.00pm - 10.00pm' and schedule.Venue='CR02' ");
 $row99=mysqli_fetch_assoc($result99);
 $row100=mysqli_fetch_assoc($result100);
 $row101=mysqli_fetch_assoc($result101);
 $row102=mysqli_fetch_assoc($result102);
 $row103=mysqli_fetch_assoc($result103);
 $row104=mysqli_fetch_assoc($result104);
 $row105=mysqli_fetch_assoc($result105);
 $row106=mysqli_fetch_assoc($result106);
 $row107=mysqli_fetch_assoc($result107);
 $row108=mysqli_fetch_assoc($result108);
 $row109=mysqli_fetch_assoc($result109);
 $row110=mysqli_fetch_assoc($result110);
 $row111=mysqli_fetch_assoc($result111);
 $row112=mysqli_fetch_assoc($result112);
 
 $result113=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='8.00am - 9.00am' and schedule.Venue='CR03' ");
 $result114=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='9.00am - 10.00am' and schedule.Venue='CR03' ");
 $result115=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='10.00am - 11.00am' and schedule.Venue='CR03' ");
 $result116=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='11.00am - 12.00pm' and schedule.Venue='CR03' ");
 $result117=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='12.00pm - 1.00pm' and schedule.Venue='CR03' ");
 $result118=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='1.00pm - 2.00pm' and schedule.Venue='CR03' ");
 $result119=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='2.00pm - 3.00pm' and schedule.Venue='CR03' ");
 $result120=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='3.00pm - 4.00pm' and schedule.Venue='CR03' ");
 $result121=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='4.00pm - 5.00pm' and schedule.Venue='CR03' ");
 $result122=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='5.00pm - 6.00pm' and schedule.Venue='CR03' ");
 $result123=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='6.00pm - 7.00pm' and schedule.Venue='CR03' ");
 $result124=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='7.00pm - 8.00pm' and schedule.Venue='CR03' ");
 $result125=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='8.00pm - 9.00pm' and schedule.Venue='CR03' ");
 $result126=mysqli_query($conn,"select *  from schedule where schedule.Day='Wednesday' and time='9.00pm - 10.00pm' and schedule.Venue='CR03' ");
 $row113=mysqli_fetch_assoc($result113);
 $row114=mysqli_fetch_assoc($result114);
 $row115=mysqli_fetch_assoc($result115);
 $row116=mysqli_fetch_assoc($result116);
 $row117=mysqli_fetch_assoc($result117);
 $row118=mysqli_fetch_assoc($result118);
 $row119=mysqli_fetch_assoc($result119);
 $row120=mysqli_fetch_assoc($result120);
 $row121=mysqli_fetch_assoc($result121);
 $row122=mysqli_fetch_assoc($result122);
 $row123=mysqli_fetch_assoc($result123);
 $row124=mysqli_fetch_assoc($result124);
 $row125=mysqli_fetch_assoc($result125);
 $row126=mysqli_fetch_assoc($result126);
 
 //Timetable Thursday
 
 $result127=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='8.00am - 9.00am' and schedule.Venue='CR01' ");
 $result128=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='9.00am - 10.00am' and schedule.Venue='CR01' ");
 $result129=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='10.00am - 11.00am' and schedule.Venue='CR01' ");
 $result130=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='11.00am - 12.00pm' and schedule.Venue='CR01' ");
 $result131=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='12.00pm - 1.00pm' and schedule.Venue='CR01' ");
 $result132=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='1.00pm - 2.00pm' and schedule.Venue='CR01' ");
 $result133=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='2.00pm - 3.00pm' and schedule.Venue='CR01' ");
 $result134=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='3.00pm - 4.00pm' and schedule.Venue='CR01' ");
 $result135=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='4.00pm - 5.00pm' and schedule.Venue='CR01' ");
 $result136=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='5.00pm - 6.00pm' and schedule.Venue='CR01' ");
 $result137=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='6.00pm - 7.00pm' and schedule.Venue='CR01' ");
 $result138=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='7.00pm - 8.00pm' and schedule.Venue='CR01' ");
 $result139=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='8.00pm - 9.00pm' and schedule.Venue='CR01' ");
 $result140=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='9.00pm - 10.00pm' and schedule.Venue='CR01' ");
 $row127=mysqli_fetch_assoc($result127);
 $row128=mysqli_fetch_assoc($result128);
 $row129=mysqli_fetch_assoc($result129);
 $row130=mysqli_fetch_assoc($result130);
 $row131=mysqli_fetch_assoc($result131);
 $row132=mysqli_fetch_assoc($result132);
 $row133=mysqli_fetch_assoc($result133);
 $row134=mysqli_fetch_assoc($result134);
 $row135=mysqli_fetch_assoc($result135);
 $row136=mysqli_fetch_assoc($result136);
 $row137=mysqli_fetch_assoc($result137);
 $row138=mysqli_fetch_assoc($result138);
 $row139=mysqli_fetch_assoc($result139);
 $row140=mysqli_fetch_assoc($result140);
 
 $result141=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='8.00am - 9.00am' and schedule.Venue='CR02' ");
 $result142=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='9.00am - 10.00am' and schedule.Venue='CR02' ");
 $result143=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='10.00am - 11.00am' and schedule.Venue='CR02' ");
 $result144=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='11.00am - 12.00pm' and schedule.Venue='CR02' ");
 $result145=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='12.00pm - 1.00pm' and schedule.Venue='CR02' ");
 $result146=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='1.00pm - 2.00pm' and schedule.Venue='CR02' ");
 $result147=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='2.00pm - 3.00pm' and schedule.Venue='CR02' ");
 $result148=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='3.00pm - 4.00pm' and schedule.Venue='CR02' ");
 $result149=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='4.00pm - 5.00pm' and schedule.Venue='CR02' ");
 $result150=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='5.00pm - 6.00pm' and schedule.Venue='CR02' ");
 $result151=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='6.00pm - 7.00pm' and schedule.Venue='CR02' ");
 $result152=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='7.00pm - 8.00pm' and schedule.Venue='CR02' ");
 $result153=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='8.00pm - 9.00pm' and schedule.Venue='CR02' ");
 $result154=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='9.00pm - 10.00pm' and schedule.Venue='CR02' ");
 $row141=mysqli_fetch_assoc($result141);
 $row142=mysqli_fetch_assoc($result142);
 $row143=mysqli_fetch_assoc($result143);
 $row144=mysqli_fetch_assoc($result144);
 $row145=mysqli_fetch_assoc($result145);
 $row146=mysqli_fetch_assoc($result146);
 $row147=mysqli_fetch_assoc($result147);
 $row148=mysqli_fetch_assoc($result148);
 $row149=mysqli_fetch_assoc($result149);
 $row150=mysqli_fetch_assoc($result150);
 $row151=mysqli_fetch_assoc($result151);
 $row152=mysqli_fetch_assoc($result152);
 $row153=mysqli_fetch_assoc($result153);
 $row154=mysqli_fetch_assoc($result154);
 
 $result155=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='8.00am - 9.00am' and schedule.Venue='CR03' ");
 $result156=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='9.00am - 10.00am' and schedule.Venue='CR03' ");
 $result157=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='10.00am - 11.00am' and schedule.Venue='CR03' ");
 $result158=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='11.00am - 12.00pm' and schedule.Venue='CR03' ");
 $result159=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='12.00pm - 1.00pm' and schedule.Venue='CR03' ");
 $result160=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='1.00pm - 2.00pm' and schedule.Venue='CR03' ");
 $result161=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='2.00pm - 3.00pm' and schedule.Venue='CR03' ");
 $result162=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='3.00pm - 4.00pm' and schedule.Venue='CR03' ");
 $result163=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='4.00pm - 5.00pm' and schedule.Venue='CR03' ");
 $result164=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='5.00pm - 6.00pm' and schedule.Venue='CR03' ");
 $result165=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='6.00pm - 7.00pm' and schedule.Venue='CR03' ");
 $result166=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='7.00pm - 8.00pm' and schedule.Venue='CR03' ");
 $result167=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='8.00pm - 9.00pm' and schedule.Venue='CR03' ");
 $result168=mysqli_query($conn,"select *  from schedule where schedule.Day='Thursday' and time='9.00pm - 10.00pm' and schedule.Venue='CR03' ");
 $row155=mysqli_fetch_assoc($result155);
 $row156=mysqli_fetch_assoc($result156);
 $row157=mysqli_fetch_assoc($result157);
 $row158=mysqli_fetch_assoc($result158);
 $row159=mysqli_fetch_assoc($result159);
 $row160=mysqli_fetch_assoc($result160);
 $row161=mysqli_fetch_assoc($result161);
 $row162=mysqli_fetch_assoc($result162);
 $row163=mysqli_fetch_assoc($result163);
 $row164=mysqli_fetch_assoc($result164);
 $row165=mysqli_fetch_assoc($result165);
 $row166=mysqli_fetch_assoc($result166);
 $row167=mysqli_fetch_assoc($result167);
 $row168=mysqli_fetch_assoc($result168);
 
 //Timetable Friday
 
 $result169=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='8.00am - 9.00am' and schedule.Venue='CR01' ");
 $result170=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='9.00am - 10.00am' and schedule.Venue='CR01' ");
 $result171=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='10.00am - 11.00am' and schedule.Venue='CR01' ");
 $result172=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='11.00am - 12.00pm' and schedule.Venue='CR01' ");
 $result173=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='12.00pm - 1.00pm' and schedule.Venue='CR01' ");
 $result174=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='1.00pm - 2.00pm' and schedule.Venue='CR01' ");
 $result175=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='2.00pm - 3.00pm' and schedule.Venue='CR01' ");
 $result176=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='3.00pm - 4.00pm' and schedule.Venue='CR01' ");
 $result177=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='4.00pm - 5.00pm' and schedule.Venue='CR01' ");
 $result178=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='5.00pm - 6.00pm' and schedule.Venue='CR01' ");
 $result179=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='6.00pm - 7.00pm' and schedule.Venue='CR01' ");
 $result180=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='7.00pm - 8.00pm' and schedule.Venue='CR01' ");
 $result181=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='8.00pm - 9.00pm' and schedule.Venue='CR01' ");
 $result182=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='9.00pm - 10.00pm' and schedule.Venue='CR01' ");
 $row169=mysqli_fetch_assoc($result169);
 $row170=mysqli_fetch_assoc($result170);
 $row171=mysqli_fetch_assoc($result171);
 $row172=mysqli_fetch_assoc($result172);
 $row173=mysqli_fetch_assoc($result173);
 $row174=mysqli_fetch_assoc($result174);
 $row175=mysqli_fetch_assoc($result175);
 $row176=mysqli_fetch_assoc($result176);
 $row177=mysqli_fetch_assoc($result177);
 $row178=mysqli_fetch_assoc($result178);
 $row179=mysqli_fetch_assoc($result179);
 $row180=mysqli_fetch_assoc($result180);
 $row181=mysqli_fetch_assoc($result181);
 $row182=mysqli_fetch_assoc($result182);
 
 $result183=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='8.00am - 9.00am' and schedule.Venue='CR02' ");
 $result184=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='9.00am - 10.00am' and schedule.Venue='CR02' ");
 $result185=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='10.00am - 11.00am' and schedule.Venue='CR02' ");
 $result186=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='11.00am - 12.00pm' and schedule.Venue='CR02' ");
 $result187=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='12.00pm - 1.00pm' and schedule.Venue='CR02' ");
 $result188=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='1.00pm - 2.00pm' and schedule.Venue='CR02' ");
 $result189=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='2.00pm - 3.00pm' and schedule.Venue='CR02' ");
 $result190=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='3.00pm - 4.00pm' and schedule.Venue='CR02' ");
 $result191=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='4.00pm - 5.00pm' and schedule.Venue='CR02' ");
 $result192=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='5.00pm - 6.00pm' and schedule.Venue='CR02' ");
 $result193=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='6.00pm - 7.00pm' and schedule.Venue='CR02' ");
 $result194=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='7.00pm - 8.00pm' and schedule.Venue='CR02' ");
 $result195=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='8.00pm - 9.00pm' and schedule.Venue='CR02' ");
 $result196=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='9.00pm - 10.00pm' and schedule.Venue='CR02' ");
 $row183=mysqli_fetch_assoc($result183);
 $row184=mysqli_fetch_assoc($result184);
 $row185=mysqli_fetch_assoc($result185);
 $row186=mysqli_fetch_assoc($result186);
 $row187=mysqli_fetch_assoc($result187);
 $row188=mysqli_fetch_assoc($result188);
 $row189=mysqli_fetch_assoc($result189);
 $row190=mysqli_fetch_assoc($result190);
 $row191=mysqli_fetch_assoc($result191);
 $row192=mysqli_fetch_assoc($result192);
 $row193=mysqli_fetch_assoc($result193);
 $row194=mysqli_fetch_assoc($result194);
 $row195=mysqli_fetch_assoc($result195);
 $row196=mysqli_fetch_assoc($result196);
 
 $result197=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='8.00am - 9.00am' and schedule.Venue='CR03' ");
 $result198=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='9.00am - 10.00am' and schedule.Venue='CR03' ");
 $result199=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='10.00am - 11.00am' and schedule.Venue='CR03' ");
 $result200=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='11.00am - 12.00pm' and schedule.Venue='CR03' ");
 $result201=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='12.00pm - 1.00pm' and schedule.Venue='CR03' ");
 $result202=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='1.00pm - 2.00pm' and schedule.Venue='CR03' ");
 $result203=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='2.00pm - 3.00pm' and schedule.Venue='CR03' ");
 $result204=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='3.00pm - 4.00pm' and schedule.Venue='CR03' ");
 $result205=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='4.00pm - 5.00pm' and schedule.Venue='CR03' ");
 $result206=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='5.00pm - 6.00pm' and schedule.Venue='CR03' ");
 $result207=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='6.00pm - 7.00pm' and schedule.Venue='CR03' ");
 $result208=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='7.00pm - 8.00pm' and schedule.Venue='CR03' ");
 $result209=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='8.00pm - 9.00pm' and schedule.Venue='CR03' ");
 $result210=mysqli_query($conn,"select *  from schedule where schedule.Day='Friday' and time='9.00pm - 10.00pm' and schedule.Venue='CR03' ");
 $row197=mysqli_fetch_assoc($result197);
 $row198=mysqli_fetch_assoc($result198);
 $row199=mysqli_fetch_assoc($result199);
 $row200=mysqli_fetch_assoc($result200);
 $row201=mysqli_fetch_assoc($result201);
 $row202=mysqli_fetch_assoc($result202);
 $row203=mysqli_fetch_assoc($result203);
 $row204=mysqli_fetch_assoc($result204);
 $row205=mysqli_fetch_assoc($result205);
 $row206=mysqli_fetch_assoc($result206);
 $row207=mysqli_fetch_assoc($result207);
 $row208=mysqli_fetch_assoc($result208);
 $row209=mysqli_fetch_assoc($result209);
 $row210=mysqli_fetch_assoc($result210);
 
 //Timetable Saturday
 
 $result211=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='8.00am - 9.00am' and schedule.Venue='CR01' ");
 $result212=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='9.00am - 10.00am' and schedule.Venue='CR01' ");
 $result213=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='10.00am - 11.00am' and schedule.Venue='CR01' ");
 $result214=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='11.00am - 12.00pm' and schedule.Venue='CR01' ");
 $result215=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='12.00pm - 1.00pm' and schedule.Venue='CR01' ");
 $result216=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='1.00pm - 2.00pm' and schedule.Venue='CR01' ");
 $result217=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='2.00pm - 3.00pm' and schedule.Venue='CR01' ");
 $result218=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='3.00pm - 4.00pm' and schedule.Venue='CR01' ");
 $result219=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='4.00pm - 5.00pm' and schedule.Venue='CR01' ");
 $result220=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='5.00pm - 6.00pm' and schedule.Venue='CR01' ");
 $result221=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='6.00pm - 7.00pm' and schedule.Venue='CR01' ");
 $result222=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='7.00pm - 8.00pm' and schedule.Venue='CR01' ");
 $result223=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='8.00pm - 9.00pm' and schedule.Venue='CR01' ");
 $result224=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='9.00pm - 10.00pm' and schedule.Venue='CR01' ");
 $row211=mysqli_fetch_assoc($result211);
 $row212=mysqli_fetch_assoc($result212);
 $row213=mysqli_fetch_assoc($result213);
 $row214=mysqli_fetch_assoc($result214);
 $row215=mysqli_fetch_assoc($result215);
 $row216=mysqli_fetch_assoc($result216);
 $row217=mysqli_fetch_assoc($result217);
 $row218=mysqli_fetch_assoc($result218);
 $row219=mysqli_fetch_assoc($result219);
 $row220=mysqli_fetch_assoc($result220);
 $row221=mysqli_fetch_assoc($result221);
 $row222=mysqli_fetch_assoc($result222);
 $row223=mysqli_fetch_assoc($result223);
 $row224=mysqli_fetch_assoc($result224);
 
 $result225=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='8.00am - 9.00am' and schedule.Venue='CR02' ");
 $result226=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='9.00am - 10.00am' and schedule.Venue='CR02' ");
 $result227=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='10.00am - 11.00am' and schedule.Venue='CR02' ");
 $result228=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='11.00am - 12.00pm' and schedule.Venue='CR02' ");
 $result229=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='12.00pm - 1.00pm' and schedule.Venue='CR02' ");
 $result230=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='1.00pm - 2.00pm' and schedule.Venue='CR02' ");
 $result231=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='2.00pm - 3.00pm' and schedule.Venue='CR02' ");
 $result232=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='3.00pm - 4.00pm' and schedule.Venue='CR02' ");
 $result233=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='4.00pm - 5.00pm' and schedule.Venue='CR02' ");
 $result234=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='5.00pm - 6.00pm' and schedule.Venue='CR02' ");
 $result235=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='6.00pm - 7.00pm' and schedule.Venue='CR02' ");
 $result236=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='7.00pm - 8.00pm' and schedule.Venue='CR02' ");
 $result237=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='8.00pm - 9.00pm' and schedule.Venue='CR02' ");
 $result238=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='9.00pm - 10.00pm' and schedule.Venue='CR02' ");
 $row225=mysqli_fetch_assoc($result225);
 $row226=mysqli_fetch_assoc($result226);
 $row227=mysqli_fetch_assoc($result227);
 $row228=mysqli_fetch_assoc($result228);
 $row229=mysqli_fetch_assoc($result229);
 $row230=mysqli_fetch_assoc($result230);
 $row231=mysqli_fetch_assoc($result231);
 $row232=mysqli_fetch_assoc($result232);
 $row233=mysqli_fetch_assoc($result233);
 $row234=mysqli_fetch_assoc($result234);
 $row235=mysqli_fetch_assoc($result235);
 $row236=mysqli_fetch_assoc($result236);
 $row237=mysqli_fetch_assoc($result237);
 $row238=mysqli_fetch_assoc($result238);
 
 $result239=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='8.00am - 9.00am' and schedule.Venue='CR03' ");
 $result240=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='9.00am - 10.00am' and schedule.Venue='CR03' ");
 $result241=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='10.00am - 11.00am' and schedule.Venue='CR03' ");
 $result242=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='11.00am - 12.00pm' and schedule.Venue='CR03' ");
 $result243=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='12.00pm - 1.00pm' and schedule.Venue='CR03' ");
 $result244=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='1.00pm - 2.00pm' and schedule.Venue='CR03' ");
 $result245=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='2.00pm - 3.00pm' and schedule.Venue='CR03' ");
 $result246=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='3.00pm - 4.00pm' and schedule.Venue='CR03' ");
 $result247=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='4.00pm - 5.00pm' and schedule.Venue='CR03' ");
 $result248=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='5.00pm - 6.00pm' and schedule.Venue='CR03' ");
 $result249=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='6.00pm - 7.00pm' and schedule.Venue='CR03' ");
 $result250=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='7.00pm - 8.00pm' and schedule.Venue='CR03' ");
 $result251=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='8.00pm - 9.00pm' and schedule.Venue='CR03' ");
 $result252=mysqli_query($conn,"select *  from schedule where schedule.Day='Saturday' and time='9.00pm - 10.00pm' and schedule.Venue='CR03' ");
 $row239=mysqli_fetch_assoc($result239);
 $row240=mysqli_fetch_assoc($result240);
 $row241=mysqli_fetch_assoc($result241);
 $row242=mysqli_fetch_assoc($result242);
 $row243=mysqli_fetch_assoc($result243);
 $row244=mysqli_fetch_assoc($result244);
 $row245=mysqli_fetch_assoc($result245);
 $row246=mysqli_fetch_assoc($result246);
 $row247=mysqli_fetch_assoc($result247);
 $row248=mysqli_fetch_assoc($result248);
 $row249=mysqli_fetch_assoc($result249);
 $row250=mysqli_fetch_assoc($result250);
 $row251=mysqli_fetch_assoc($result251);
 $row252=mysqli_fetch_assoc($result252);
 
 //Timetable Sunday
 
 $result253=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='8.00am - 9.00am' and schedule.Venue='CR01' ");
 $result254=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='9.00am - 10.00am' and schedule.Venue='CR01' ");
 $result255=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='10.00am - 11.00am' and schedule.Venue='CR01' ");
 $result256=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='11.00am - 12.00pm' and schedule.Venue='CR01' ");
 $result257=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='12.00pm - 1.00pm' and schedule.Venue='CR01' ");
 $result258=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='1.00pm - 2.00pm' and schedule.Venue='CR01' ");
 $result259=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='2.00pm - 3.00pm' and schedule.Venue='CR01' ");
 $result260=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='3.00pm - 4.00pm' and schedule.Venue='CR01' ");
 $result261=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='4.00pm - 5.00pm' and schedule.Venue='CR01' ");
 $result262=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='5.00pm - 6.00pm' and schedule.Venue='CR01' ");
 $result263=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='6.00pm - 7.00pm' and schedule.Venue='CR01' ");
 $result264=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='7.00pm - 8.00pm' and schedule.Venue='CR01' ");
 $result265=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='8.00pm - 9.00pm' and schedule.Venue='CR01' ");
 $result266=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='9.00pm - 10.00pm' and schedule.Venue='CR01' ");
 $row253=mysqli_fetch_assoc($result253);
 $row254=mysqli_fetch_assoc($result254);
 $row255=mysqli_fetch_assoc($result255);
 $row256=mysqli_fetch_assoc($result256);
 $row257=mysqli_fetch_assoc($result257);
 $row258=mysqli_fetch_assoc($result258);
 $row259=mysqli_fetch_assoc($result259);
 $row260=mysqli_fetch_assoc($result260);
 $row261=mysqli_fetch_assoc($result261);
 $row262=mysqli_fetch_assoc($result262);
 $row263=mysqli_fetch_assoc($result263);
 $row264=mysqli_fetch_assoc($result264);
 $row265=mysqli_fetch_assoc($result265);
 $row266=mysqli_fetch_assoc($result266);
 
 $result267=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='8.00am - 9.00am' and schedule.Venue='CR02' ");
 $result268=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='9.00am - 10.00am' and schedule.Venue='CR02' ");
 $result269=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='10.00am - 11.00am' and schedule.Venue='CR02' ");
 $result270=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='11.00am - 12.00pm' and schedule.Venue='CR02' ");
 $result271=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='12.00pm - 1.00pm' and schedule.Venue='CR02' ");
 $result272=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='1.00pm - 2.00pm' and schedule.Venue='CR02' ");
 $result273=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='2.00pm - 3.00pm' and schedule.Venue='CR02' ");
 $result274=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='3.00pm - 4.00pm' and schedule.Venue='CR02' ");
 $result275=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='4.00pm - 5.00pm' and schedule.Venue='CR02' ");
 $result276=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='5.00pm - 6.00pm' and schedule.Venue='CR02' ");
 $result277=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='6.00pm - 7.00pm' and schedule.Venue='CR02' ");
 $result278=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='7.00pm - 8.00pm' and schedule.Venue='CR02' ");
 $result279=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='8.00pm - 9.00pm' and schedule.Venue='CR02' ");
 $result280=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='9.00pm - 10.00pm' and schedule.Venue='CR02' ");
 $row267=mysqli_fetch_assoc($result267);
 $row268=mysqli_fetch_assoc($result268);
 $row269=mysqli_fetch_assoc($result269);
 $row270=mysqli_fetch_assoc($result270);
 $row271=mysqli_fetch_assoc($result271);
 $row272=mysqli_fetch_assoc($result272);
 $row273=mysqli_fetch_assoc($result273);
 $row274=mysqli_fetch_assoc($result274);
 $row275=mysqli_fetch_assoc($result275);
 $row276=mysqli_fetch_assoc($result276);
 $row277=mysqli_fetch_assoc($result277);
 $row278=mysqli_fetch_assoc($result278);
 $row279=mysqli_fetch_assoc($result279);
 $row280=mysqli_fetch_assoc($result280);
 
 $result281=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='8.00am - 9.00am' and schedule.Venue='CR03' ");
 $result282=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='9.00am - 10.00am' and schedule.Venue='CR03' ");
 $result283=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='10.00am - 11.00am' and schedule.Venue='CR03' ");
 $result284=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='11.00am - 12.00pm' and schedule.Venue='CR03' ");
 $result285=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='12.00pm - 1.00pm' and schedule.Venue='CR03' ");
 $result286=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='1.00pm - 2.00pm' and schedule.Venue='CR03' ");
 $result287=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='2.00pm - 3.00pm' and schedule.Venue='CR03' ");
 $result288=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='3.00pm - 4.00pm' and schedule.Venue='CR03' ");
 $result289=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='4.00pm - 5.00pm' and schedule.Venue='CR03' ");
 $result290=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='5.00pm - 6.00pm' and schedule.Venue='CR03' ");
 $result291=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='6.00pm - 7.00pm' and schedule.Venue='CR03' ");
 $result292=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='7.00pm - 8.00pm' and schedule.Venue='CR03' ");
 $result293=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='8.00pm - 9.00pm' and schedule.Venue='CR03' ");
 $result294=mysqli_query($conn,"select *  from schedule where schedule.Day='Sunday' and time='9.00pm - 10.00pm' and schedule.Venue='CR03' ");
 $row281=mysqli_fetch_assoc($result281);
 $row282=mysqli_fetch_assoc($result282);
 $row283=mysqli_fetch_assoc($result283);
 $row284=mysqli_fetch_assoc($result284);
 $row285=mysqli_fetch_assoc($result285);
 $row286=mysqli_fetch_assoc($result286);
 $row287=mysqli_fetch_assoc($result287);
 $row288=mysqli_fetch_assoc($result288);
 $row289=mysqli_fetch_assoc($result289);
 $row290=mysqli_fetch_assoc($result290);
 $row291=mysqli_fetch_assoc($result291);
 $row292=mysqli_fetch_assoc($result292);
 $row293=mysqli_fetch_assoc($result293);
 $row294=mysqli_fetch_assoc($result294); */
 ?>